name: verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Cache Nix store
      id: cache-nix
      uses: actions/cache@v4
      with:
        path: /nix
        key: ${{ runner.os }}-nix

    - name: Install dependencies
      run: nix develop --profile ./oj-env

    - name: Run tests
      # env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        # GH_PAT: ${{ secrets.GH_PAT }}
      # run: oj-verify all
      run: nix develop ./oj-env --command bash -c "oj-verify run"
